# Generated by Django 5.1.2 on 2024-11-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('disease_category', models.CharField(choices=[('hypertension', 'Hypertension'), ('diabetes', 'Diabetes'), ('asthma', 'Asthma'), ('arthritis', 'Arthritis'), ('other', 'Other')], max_length=20)),
                ('nature', models.CharField(choices=[('better', 'Better'), ('improving', 'Improving'), ('worsen', 'Worsen')], max_length=10)),
                ('address', models.TextField()),
            ],
        ),
    ]
